SET NAMES utf8mb4;
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS Pokemon_TCG;
CREATE SCHEMA Pokemon_TCG;
USE Pokemon_TCG;

CREATE TABLE Tipo(
tipo_id INT UNSIGNED NOT NULL,
tipo VARCHAR(45) NOT NULL,

PRIMARY KEY(tipo_id)
);

CREATE TABLE Elementos(
elemento_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
tipo_id INT UNSIGNED NOT NULL,
debil_id INT UNSIGNED NOT NULL,
eficaz_id INT UNSIGNED NOT NULL,

PRIMARY KEY(elemento_id),
CONSTRAINT fk_Elemento_Tipo FOREIGN KEY (tipo_id) REFERENCES Tipo (tipo_id) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_Elemento_Debil FOREIGN KEY (debil_id) REFERENCES Tipo (tipo_id) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_Elemento_Eficaz FOREIGN KEY (eficaz_id) REFERENCES Tipo (tipo_id) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Pokemon_base(
poke_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
nombre VARCHAR(45) NOT NULL,
descripcion VARCHAR(45) NOT NULL,
elemento_id INT NOT NULL,
dano SMALLINT NOT NULL,
fase TINYINT NOT NULL,
costo_habilidad TINYINT NOT NULL,
costo_retirada TINYINT NOT NULL,
vida SMALLINT NOT NULL,

PRIMARY KEY(poke_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Cartas_Entrenador(
efecto_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
nombre VARCHAR(45) NOT NULL,
descripcion VARCHAR(45) NOT NULL,
efecto VARCHAR(45) NOT NULL,

PRIMARY KEY(efecto_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Energia(
energia_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
tipo_id INT UNSIGNED NOT NULL,

PRIMARY KEY(energia_id),
CONSTRAINT fk_Energia_Tipo FOREIGN KEY (tipo_id) REFERENCES Tipo (tipo_id) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Jugador(
jugador_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
nombre VARCHAR(45) NOT NULL,
contrasena VARCHAR(45) NOT NULL,
nivel SMALLINT,
rango SMALLINT,
monedas SMALLINT,
cristales SMALLINT,
creditos SMALLINT,

PRIMARY KEY(jugador_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Mazo_base(
mazo_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
num_poke TINYINT,
num_efect TINYINT,
num_effecto TINYINT,
activo TINYINT NOT NULL,

PRIMARY KEY(mazo_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Inventario(
inventory_id INT UNSIGNED NOT NULL AUTO_INCREMENT,

jugador_id INT UNSIGNED NOT NULL,
poke_id INT UNSIGNED NOT NULL,
efecto_id INT UNSIGNED NOT NULL,
energia_id INT UNSIGNED NOT NULL,
mazo_id INT UNSIGNED NOT NULL,

PRIMARY KEY(inventory_id),

CONSTRAINT fk_Inventario_Jugador FOREIGN KEY (jugador_id) REFERENCES Jugador (jugador_id) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_Inventario_Poke FOREIGN KEY (poke_id) REFERENCES Pokemon_base (poke_id) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_Inventario_Entrenador FOREIGN KEY (efecto_id) REFERENCES Cartas_Entrenador (efecto_id) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_Inventario_Energia FOREIGN KEY (energia_id) REFERENCES Energia (energia_id) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_Inventario_Mazo FOREIGN KEY (mazo_id) REFERENCES Mazo_base (mazo_id) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Banca(
banca_id INT UNSIGNED NOT NULL AUTO_INCREMENT,

jugador_id INT UNSIGNED NOT NULL,
cartas_poke INT UNSIGNED NOT NULL,
cartas_efect INT UNSIGNED NOT NULL,
cartas_energi INT UNSIGNED NOT NULL,

num_cartas_victoria TINYINT,
tamaño_mazo TINYINT,

PRIMARY KEY(banca_id),
CONSTRAINT fk_Banca_Jugador FOREIGN KEY (jugador_id) REFERENCES Jugador (jugador_id) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Turno(
turno_id INT UNSIGNED NOT NULL AUTO_INCREMENT,

jugador_id INT UNSIGNED NOT NULL,
banca_id INT UNSIGNED NOT NULL,
poke_jugada INT UNSIGNED NOT NULL,
entrena_jugada INT UNSIGNED NOT NULL,
energi_jugada INT UNSIGNED NOT NULL,

PRIMARY KEY(turno_id),
CONSTRAINT fk_Turno_Jugador FOREIGN KEY (jugador_id) REFERENCES Jugador (jugador_id) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_Turno_Banca FOREIGN KEY (banca_id) REFERENCES Banca (banca_id) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_Turno_Poke FOREIGN KEY (poke_jugada) REFERENCES Pokemon_base (poke_id) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_Turno_Entrenador FOREIGN KEY (entrena_jugada) REFERENCES Cartas_Entrenador (efecto_id) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_Turno_Energia FOREIGN KEY (energi_jugada) REFERENCES Energia (energia_id) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Partida(
partida_id INT UNSIGNED NOT NULL AUTO_INCREMENT,

jugador1_id INT UNSIGNED NOT NULL,
jugador2_id INT UNSIGNED NOT NULL,
turno_id INT UNSIGNED NOT NULL,
ganador INT UNSIGNED NOT NULL,

duracion TINYINT, -- en segundos
fecha TIMESTAMP,

PRIMARY KEY(partida_id),
CONSTRAINT fk_Partida_Jugador1 FOREIGN KEY (jugador1_id) REFERENCES Jugador (jugador_id) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_Partida_Jugador2 FOREIGN KEY (jugador2_id) REFERENCES Jugador (jugador_id) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_Partida_Turno FOREIGN KEY (turno_id) REFERENCES Turno (turno_id) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Precio(
precio_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
precio SMALLINT,

PRIMARY KEY(precio_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Monedas(
monedas_id INT UNSIGNED NOT NULL AUTO_INCREMENT,

precio_id INT UNSIGNED NOT NULL,

cant_monedas SMALLINT,

PRIMARY KEY(monedas_id),
CONSTRAINT fk_Monedas_Precio FOREIGN KEY (precio_id) REFERENCES Precio (precio_id) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Cristales(
cristales_id INT UNSIGNED NOT NULL AUTO_INCREMENT,

precio_id INT UNSIGNED NOT NULL,

cant_cristales SMALLINT,

PRIMARY KEY(cristales_id),
CONSTRAINT fk_Cristales_Precio FOREIGN KEY (precio_id) REFERENCES Precio (precio_id) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Creditos(
creditos_id INT UNSIGNED NOT NULL AUTO_INCREMENT,

precio_id INT UNSIGNED NOT NULL,

cant_creditos SMALLINT,

PRIMARY KEY(creditos_id),
CONSTRAINT fk_Crediros_Precio FOREIGN KEY (precio_id) REFERENCES Precio (precio_id) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Poke_carta(
poke_carta_id INT UNSIGNED NOT NULL AUTO_INCREMENT,

precio_id INT UNSIGNED NOT NULL,
poke_id INT UNSIGNED NOT NULL,

PRIMARY KEY(poke_carta_id),
CONSTRAINT fk_Poke_Carta_Precio FOREIGN KEY (precio_id) REFERENCES Precio (precio_id) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_PC_Poke FOREIGN KEY (poke_id) REFERENCES Poke (poke_id) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Entrena_carta(
entrena_carta_id INT UNSIGNED NOT NULL AUTO_INCREMENT,

precio_id INT UNSIGNED NOT NULL,
efecto_id INT UNSIGNED NOT NULL,

PRIMARY KEY(entrena_carta_id),
CONSTRAINT fk_EC_Entrenador FOREIGN KEY (efecto_id) REFERENCES Cartas_Entrenador (efecto_id) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Energ_carta(
energ_carta_id INT UNSIGNED NOT NULL AUTO_INCREMENT,

precio_id INT UNSIGNED NOT NULL,
energia_id INT UNSIGNED NOT NULL,

PRIMARY KEY(energ_carta_id),
CONSTRAINT fk_EnC_Energia FOREIGN KEY (energia_id) REFERENCES Energia (energia_id) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Tienda_base(
tienda_id INT UNSIGNED NOT NULL AUTO_INCREMENT,

poke_carta_id INT UNSIGNED NOT NULL,
energ_carta_id INT UNSIGNED NOT NULL,
entrena_carta_id INT UNSIGNED NOT NULL,
monedas_id INT UNSIGNED NOT NULL,
cristales_id INT UNSIGNED NOT NULL,
creditos_id INT UNSIGNED NOT NULL,

PRIMARY KEY(tienda_id),
CONSTRAINT fk_Tienda_Poke_Carta FOREIGN KEY (poke_carta_id) REFERENCES Poke_Carta (poke_carta_id) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_Tienda_Entrena_Carta FOREIGN KEY (energ_carta_id) REFERENCES Entrena_Carta (entrena_carta_id) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_Tienda_Energ_Carta FOREIGN KEY (entrena_carta_id) REFERENCES Energ_Carta (energ_carta_id) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_Tienda_Monedas FOREIGN KEY (monedas_id) REFERENCES Monedas (monedas_id) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_Tienda_Cristales FOREIGN KEY (cristales_id) REFERENCES Cristales (cristales_id) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_Tienda_Creditos FOREIGN KEY (creditos_id) REFERENCES Creditos (creditos_id) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Pack_de_cartas(
pack_id INT UNSIGNED NOT NULL AUTO_INCREMENT,

poke_id INT UNSIGNED NOT NULL,
efecto_id INT UNSIGNED NOT NULL,
energia_id INT UNSIGNED NOT NULL,

PRIMARY KEY(pack_id),
CONSTRAINT fk_Pack_Poke FOREIGN KEY (poke_id) REFERENCES Poke (poke_id) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_Pack_Entrenador FOREIGN KEY (efecto_id) REFERENCES Entrenador (efecto_id) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_Pack_Energia FOREIGN KEY (energia_id) REFERENCES Energia (energia_id) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Pase(
pase_id INT UNSIGNED NOT NULL AUTO_INCREMENT,

jugador_id INT UNSIGNED NOT NULL,
pack_id INT UNSIGNED NOT NULL,

cristales SMALLINT,
nivel SMALLINT,

PRIMARY KEY(pase_id),
CONSTRAINT fk_Pack_Jugador FOREIGN KEY (jugador_id) REFERENCES Jugador (jugador_id) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_Pack_Pack_de_cartas FOREIGN KEY (pack_id) REFERENCES Pack_de_cartas (pack_id) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;